/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

[scriptable, uuid(b44d74db-c9d6-41dd-98ae-a56918d6e6ad)]
interface nsINetworkInterfaceListService : nsISupports
{
  void getInterfaceList(in nsINetowkrInterfaceListCallback callback);
}

[scriptable, uuid(b44d74db-c9d6-41dd-98ae-a56918d6e6ad)]
interface nsINetworkInterfaceListCallback : nsISupports
{
  void onInterfaceListGot(in nsINetworkInterfaceList list);
}

[scriptable, uuid(b44d74db-c9d6-41dd-98ae-a56918d6e6ad)]
interface nsINetworkInterfaceList : nsISupports
{
  /**
   * Number of the network interfaces that is available.
   */
  int getNumberOfInterface();
  nsINetworkInterface getInterface(int interfaceIndex);
}
